import jsPDF from "jspdf";
import "jspdf-autotable";

interface InitPDFReportProps {
  title: string;
  filters?: string[];
  userName?: string;
  programType?: string;
}

const getBase64ImageFromURL = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.setAttribute("crossOrigin", "anonymous");
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx?.drawImage(img, 0, 0);
      const dataURL = canvas.toDataURL("image/png");
      resolve(dataURL);
    };
    img.onerror = (error) => {
      reject(error);
    };
    img.src = url;
  });
};

export const initPDFReport = async ({
  title,
  filters = [],
  userName = "Admin",
  programType,
}: InitPDFReportProps) => {
  const doc = new jsPDF("p", "mm", "a4");
  const imgPath = "/temp-logo.png";
  const address =
    "Jl. Akses Kereta Cepat Halim Perdanakusumah, Kel. Halim Perdanakusumah, Kec. Makasar, Jakarta Timur, 13610 ";

  // Add Logo
  try {
    const imgData = await getBase64ImageFromURL(imgPath);
    doc.addImage(imgData, "PNG", 15, 10, 25, 25); // x, y, w, h
  } catch (e) {
    console.warn("Logo could not be added", e);
  }

  // Company Name / Header
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Kereta Cepat Indonesia China", 50, 20);

  // Address
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const maxWidth = 100; // Reduced to 100 to avoid overlap with "Generated by" (approx x=150+)
  const addressLines = doc.splitTextToSize(address, maxWidth);
  doc.text(addressLines, 50, 26);

  // Calculate dynamic start Y for Title based on address lines or logo height
  // Logo bottom is roughly 10 + 25 = 35
  // Address starts at 26.
  // 1 line ~ 4-5mm.
  // We want to ensure Title is below the lowest point.

  // Estimate address height
  const lineHeight = 4;
  const addressBottomY = 26 + addressLines.length * lineHeight;
  const logoBottomY = 35;
  const headerBottomY = Math.max(addressBottomY, logoBottomY);

  const titleY = headerBottomY + 10;

  // Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 15, titleY);

  // Filters Info
  let currentY = titleY + 7;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  if (filters.length > 0) {
    filters.forEach((filter) => {
      doc.text(filter, 15, currentY);
      currentY += 5;
    });
  } else {
    // Just add a small gap if no filters
    currentY += 0;
  }

  // Add a line separator
  const lineY = currentY + 2;
  doc.setLineWidth(0.5);
  doc.line(15, lineY, 195, lineY);

  // Return startY for the table
  const startY = lineY + 5;

  // Footer (Page Numbers) & Metadata
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text(`Generated by: ${userName}`, 195, 20, { align: "right" });
  doc.text(`Date: ${new Date().toLocaleString("id-ID")}`, 195, 25, {
    align: "right",
  });
  doc.setTextColor(0); // Reset

  return { doc, startY };
};
