import jsPDF from "jspdf";
import "jspdf-autotable";

interface InitPDFReportProps {
  title: string;
  filters?: string[];
  userName?: string;
  programType?: string;
}

const getBase64ImageFromURL = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.setAttribute("crossOrigin", "anonymous");
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx?.drawImage(img, 0, 0);
      const dataURL = canvas.toDataURL("image/png");
      resolve(dataURL);
    };
    img.onerror = (error) => {
      reject(error);
    };
    img.src = url;
  });
};

export const initPDFReport = async ({
  title,
  filters = [],
  userName = "Admin",
  programType,
}: InitPDFReportProps) => {
  const doc = new jsPDF("l", "mm", "a4");
  const imgPath = "/temp-logo.png";

  // Custom Address Block
  const companyName = "KCIC Halim Office";
  const address =
    "Jl. Akses Kereta Cepat Halim Perdanakusumah, Desa/Kelurahan Halim Perdana Kusuma, Kec. Makasar, Kota Adm. Jakarta Timur, Provinsi DKI Jakarta. 13610";
  const contactInfo = [
    "WhatsApp Call Center & Chat: 0811-8888-111",
    "Customer Service: cs@kcic.co.id",
    "Office Purpose: sekretariat@kcic.co.id",
  ];

  // Add Logo
  try {
    const imgData = await getBase64ImageFromURL(imgPath);
    doc.addImage(imgData, "PNG", 15, 10, 25, 25); // x, y, w, h
  } catch (e) {
    console.warn("Logo could not be added", e);
  }

  // Header Text Configuration
  const startX = 45; // Text starts after logo
  let currentY = 15;

  // Company Name
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(companyName, startX, currentY);

  // Address
  currentY += 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const maxWidth = 220;
  const addressLines = doc.splitTextToSize(address, maxWidth);
  doc.text(addressLines, startX, currentY);

  // Contact Info
  currentY += addressLines.length * 4 + 2;
  doc.setFontSize(8);
  contactInfo.forEach((line) => {
    doc.text(line, startX, currentY);
    currentY += 4;
  });

  // Header Separator Line
  const lineY = Math.max(currentY + 2, 40); // Ensure minimal height
  doc.setLineWidth(0.5);
  doc.line(15, lineY, 282, lineY);

  // Document Title
  const titleY = lineY + 10;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 148.5, titleY, { align: "center" });

  // Metadata (Right side below header line)
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated by: ${userName}`, 282, lineY + 5, { align: "right" });
  doc.text(`Date: ${new Date().toLocaleString("id-ID")}`, 282, lineY + 9, {
    align: "right",
  });
  doc.setTextColor(0);

  // Filters Info
  let filterY = titleY + 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  if (filters.length > 0) {
    filters.forEach((filter) => {
      doc.text(filter, 15, filterY);
      filterY += 5;
    });
  }

  // Return startY for the table
  const startY = filterY + 5;

  return { doc, startY };
};
